vim.opt.wrap = false -- turn off line wrapping
vim.o.number = true -- line numbers
vim.o.relativenumber = true -- relative line numbers
vim.opt.expandtab = true -- spaces instead of tabs
vim.opt.shiftwidth = 4 -- size of indent
vim.opt.tabstop = 4 -- number of spaces a tab counts for
vim.opt.softtabstop = 4 -- number of spaces a tab counts for while editing
vim.opt.belloff = "all" -- turn off the bell
vim.opt.visualbell = false -- turn off the bell
vim.opt.errorbells = false -- turn off the bell
vim.o.mouse = "a" -- enable mouse mode
vim.o.showmode = false -- don't show the mode, it is on the statusline
vim.o.breakindent = true -- wrapped lines have an indentation level starting at the indentation of the line itself (e.g., hanging indents)
vim.opt.linebreak = true -- break on words instead of letters
vim.o.undofile = true -- enable undo/redo changes after closing and reopening a file
vim.o.ignorecase = true -- case-insensitive searching (prepend `\C` for case sensitive)
vim.o.smartcase = true -- case-insensitive unless search term contains an uppercase letter
vim.o.signcolumn = "yes" -- show git diffs, LSP errors/warnings, breakpoints, etc.
vim.o.updatetime = 250 -- how long to wait before triggering background events (writing to swap, CursorHold autocommand, etc.)
vim.o.timeoutlen = 300 -- time to wait for completing multi-key mapped command/key sequence (e.g., jk together for <Esc>)
vim.o.splitright = true -- split to right by default
vim.o.splitbelow = true -- split to bottom by default
vim.o.list = true -- makes whitespace characters visable
vim.opt.listchars = { tab = "» ", trail = "·", nbsp = "␣" }
vim.o.inccommand = "split" -- preview subsitutions live/during typing
vim.o.cursorline = true -- show which line the cursor is on
vim.o.scrolloff = 10 -- minimum number of lines to keep above/below the cursor
vim.o.confirm = true -- if performing an action that would fail due to unsaved changes, show a dialog for confirmation
